import { Inter } from "next/font/google";
import Navbar from './components/ui/Navbar'; // Asegúrate de que las rutas sean correctas
import Footer from './components/ui/Footer';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-tomato">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
